[tool.poetry]
name = "orvorlesung"
version = "0.1.0"
description = ""
authors = ["jonasstDev <jonas.strehler@t-online.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
jupyter = "^1.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
